python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.999 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.99 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.98 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.95 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.90 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.75 
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.50
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.25
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.10
python main.py algos='[multi_step, single_step]' wandb=True algos.multi_step.gamma=0.01