task: "Nav2D-v0"
algo_name: "dqn"
seed: 0
logdir: "log"
pretrained_encoder_path: null
exp_name: ""
freeze_encoder: false

# eval arguments
logger: "wandb" 
wandb_project_name: "nav2d"
wandb_entity: "maxrudolph"
capture_video: false
save_buffer_name: null
save_model: False

use_wandb: False
render_freq: 50000
eval_freq: 1000
train_steps: 3000000
torch_deterministic: True
cuda: True



env:
  max_timesteps: 50
  grid_size: 7
  num_obstacles: 0
  obstacle_diameter: 1
  static_goal: true

rl: 
  learning_rate: 0.00025
  buffer_size: 10000
  learning_starts: 10000
  batch_size: 128
  tau: 1.0
  gamma: 0.99
  train_freq: 1
  start_epsilon: 1.0
  end_epsilon: 0.05
  exploration_fraction: 0.5 # the fraction of `total-timesteps` it takes from start-e to go end-e
  num_envs: 1
  target_network_frequency: 500
  train_frequency: 10


# network arguments
encoder:
  hidden_layers: [64, 64, 96, 128]
  num_pooling: 2
  activation: "relu"
  layer_norm: false
  output_dim: 64
