task: "Nav2D-v0"
algo_name: "dqn"
seed: 0
logdir: "log"
pretrained_encoder_path: null
name: ""
freeze_encoder: false

# eval arguments
logger: "wandb" 
wandb_project: "nav2d"
wandb_entity: "maxrudolph"
watch: false
save_buffer_name: null
use_wandb: False
render_freq: 50000
eval_freq: 1000
train_steps: 3000000


env:
  max_timesteps: 50
  grid_size: 7
  num_obstacles: 0
  obstacle_diameter: 1
  static_goal: true

rl: 
  learning_rate: 0.001
  buffer_size: 100000
  learning_starts: 1000
  batch_size: 32
  tau: 0.005
  gamma: 0.95
  train_freq: 1
  exploration_initial_eps: 0.9
  exploration_final_eps: 0.2
  device: "cuda"

# network arguments
encoder_args:
  hidden_layers: [64, 64, 96, 128]
  num_pooling: 2
  activation: "relu"
  layer_norm: false
  output_dim: 64
