# logdir: 'results'
# dataset: '/nfs/homes/bisim/rrai/action-bisimulation/datasets/nav2d_dataset_s0_e0.5_size1000000__k_steps_0.hdf5'
# wandb: False
# seed: 0 
# n_epochs: 10
# batch_size: 256
# met_log_freq: 10
# img_log_freq: 1000
# train_single_step: True
# single_step_path: None
# trained_model_dir: '/nfs/homes/bisim/rrai/action-bisimulation/trained_models/'
# heatmap_dir: '/nfs/homes/bisim/rrai/action-bisimulation/heatmaps/'

# defaults:
#   - algos: single_step
#   - /networks@encoder: cnn
#   - /networks@forward: mlp
#   - /networks@inverse: mlp

logdir: 'results'
dataset: '/nfs/homes/bisim/rrai/action-bisimulation/datasets/nav2d_dataset_s0_e0.5_size1000000__k_steps_0.hdf5'
# wandb: True
wandb: False
seed: 0
n_epochs: 10
batch_size: 256
met_log_freq: 10 # logging every this many number of steps (met = metrics)
img_log_freq: 1000

defaults:
  - algos: [single_step, multi_step]
  # - algos: single_step
  - /networks@encoder: cnn
  - /networks@forward: mlp
  - /networks@inverse: mlp
