logdir: 'results'
dataset: '/u/mrudolph/documents/action-bisimulation/datasets/nav2d_dataset_s0_e0.5_size10000__k_steps_0.hdf5'
wandb: False
seed: 0 
n_epochs: 20
batch_size: 256
met_log_freq: 10
img_log_freq: 3000

defaults:
  - algos: single_step
  - /networks@encoder: cnn
  - /networks@forward: mlp
  - /networks@inverse: mlp
