# @package algos.acro
name: acro
forward_weight: 0
l1_penalty: 0.001
learning_rate: 0.0001
weight_decay: 0.0
resume_path: ''
control_type: inverse_dynamics
train_stop_epochs: 500 # stop after this many training
use_gen_nets: True
dynamic_l1_penalty: True
k_steps: 1 # 1 is equivalent to single_step because 1 - 1 = 0 which is just obs_next
defaults:
  - networks/cnn@encoder
  - networks/mlp@forward
  - networks/mlp@inverse
