# @package algos.infonce
name: infonce
forward_weight: 0
l1_penalty: 0.001
learning_rate: 0.0001
weight_decay: 0.0
resume_path: ''
proj_dim: 128
train_stop_epochs: 100
temperature: 0.1
use_gen_nets: True
dynamic_l1_penalty: True
defaults:
  - networks/cnn@encoder
  - networks/mlp@forward
  - networks/mlp@inverse
