# @package algos.multi_step
name: multi_step
tau: 0.005
sync_freq: 1
gamma: 0.98
learning_rate: 0.0001
weight_decay: 0.00001
resume_path: null
ss_train_warmup_epochs: 0

base_case_path: ''
use_states_with_same_action: False # behavioral
forward_model_steps_per_batch: 1 # lagging behind is already implemented
warm_start_ms_with_ss: False
multi_step_forward_loss: l1
reset_forward_model_every: 3000

base_encoder_cfg:
  type: cnn
  input_channels: 3 
  hidden_layers: [64, 64, 64, 96, 96, 128] #based on cnn in config?
  num_pooling: 2
  acti: relu
  use_layer_norm: False
  output_dim: 64



defaults:
  - networks/cnn@encoder
  - networks/mlp@forward
  - networks/mlp@inverse
